export const INIT_DATA = 'INIT_DATA'

export const PROJECT_ADD = 'PROJECT_ADD'
export const PROJECT_DELETE = 'PROJECT_DELETE'
export const PROJECT_ACTIVE = 'PROJECT_ACTIVE'
export const PROJECT_DIALOG_STATUS = 'PROJECT_DIALOG_STATUS'

export const GROUP_ADD = 'GROUP_ADD'
export const GROUP_DELETE = 'GROUP_DELETE'
export const GROUP_EDITING = 'GROUP_EDITING'
export const GROUP_EDIT = 'GROUP_EDIT'
export const GROUP_ACTIVE = 'GROUP_ACTIVE'
export const GROUP_DEACTIVE = 'GROUP_DEACTIVE'